Helped Migrate to Appwrite Version 0.15.^ and Appwrite SDK 6.0.0
appwrite/demo-almost-netflix-for-flutter pull request #2
Opened 2022-07-25 11:24 UTC by kekavc24

Helped :
* Migrate the repo to use Appwrite version 0.15.^ and Appwrite SDK 6.0.0
* Fixed some but not all linter issues. I left the various unused variables. I assumed you had planned to use them in future.

2022-07-25 20:57 UTC, stnguyen90 commented
Thanks so much for your contribution! 🙏 Let me look into who can review this so we can get it merged in!

2022-07-27 18:57 UTC, brandonroberts requested changes
Overall LGTM, just needs the bucketId to be updated. Tested and working locally

2022-07-27 18:57 UTC, brandonroberts commented on lib/providers/watchlist.dart
> +  static const String _bucketId = "Your bucket ID";
The `_bucketId` is **"default"**

2022-07-27 18:57 UTC, brandonroberts commented on lib/providers/entry.dart
> +  static const String _bucketId = "Your bucket ID";
Should be **"default"**

2022-07-27 19:34 UTC, brandonroberts approved these changes
LGTM

2022-07-27 19:35 UTC, merged

2022-07-27 19:35 UTC, brandonroberts commented
Thanks @kekavc24! Nice work!

2022-07-27 19:42 UTC, kekavc24 commented
No problem 💯 Thought I'd help since maybe you guys are busy making Appwrite Awesome 😜😎