Upgrade to appwrite 1.0
appwrite/demo-almost-netflix-for-flutter pull request #5
Opened 2022-10-26 16:28 UTC by letsintegreat

## What does this PR do?

Upgrades the app to use appwrite 1.0

## Test Plan

I have used this [blogpost](https://dev.to/appwrite/did-we-just-build-a-netflix-clone-with-appwrite-28ok) to setup the project, and tested the app in an emulator.

Here are some ids used:
projectID: almostNetflix2
databaseID: default
collectionID: movies, watchlists
bucketID: default

## Related PRs and Issues

Closes https://github.com/appwrite/appwrite/issues/4269

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-10-26 23:13 UTC, stnguyen90 requested changes
@letsintegreat Great PR! 🤯 Would you please also address the following:

- [ ] Make use of the `ID`, `Permission`, and `Role` helpers where applicable rather than using magic strings
- [ ] Remove `createdAt` from the watchlist collection since the attribute is built in now.
- [ ] genres, tags, and cast in Entry should be lists

The app doesn't run smoothly for me and crashes quite often. Does that happen for you?

2022-10-31 16:24 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-07 20:39 UTC, letsintegreat commented
@stnguyen90 Hey, sorry for the late reply, I got busy with college stuff. Anyways, now I am back and will try to make the PR merge-ready ASAP.

So, I am working to address the last 2 points. Though I am not sure what ID, Permission, and Role helpers are. Can you please elaborate on the first point while I work on the others? Thanks.

2022-11-07 20:53 UTC, stnguyen90 commented
> So, I am working to address the last 2 points. Though I am not sure what ID, Permission, and Role helpers are. Can you please elaborate on the first point while I work on the others? Thanks.

For example, see https://github.com/appwrite/playground-for-flutter/blob/ceea7c3b491506d4c1f7c8da5149153824092eec/lib/main.dart#L103-L108.

2022-12-09 20:35 UTC, letsintegreat commented
> @letsintegreat Great PR! 🤯 Would you please also address the following:
> 
> * [ ]  Make use of the `ID`, `Permission`, and `Role` helpers where applicable rather than using magic strings
> * [ ]  Remove `createdAt` from the watchlist collection since the attribute is built in now.
> * [ ]  genres, tags, and cast in Entry should be lists
> 
> The app doesn't run smoothly for me and crashes quite often. Does that happen for you?

@stnguyen90 Hey, I have addressed all the 3 points, please review the changes!

2023-01-05 17:29 UTC, stnguyen90 requested changes

2023-01-05 17:29 UTC, stnguyen90 commented on lib/data/entry.dart
> +  final List<String> genres;
After logging in I got this error:

> `_TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>')`

2023-01-05 17:29 UTC, stnguyen90 commented on lib/providers/watchlist.dart
>          documentId: 'unique()',
Please replace this with `ID.unique()`

2023-01-05 17:29 UTC, stnguyen90 commented on lib/providers/account.dart
> +  Account? get current => _current;
Please replace the `unique()` in this file too.

2023-01-19 13:21 UTC, letsintegreat commented on lib/data/entry.dart
> +  final List<String> genres;
@stnguyen90 I am not able to reproduce this error? I have addressed the rest of the two requests though.

2023-01-19 19:54 UTC, stnguyen90 commented on lib/data/entry.dart
> +  final List<String> genres;
@letsintegreat is `genres` a String Array attribute in your instance? Do you have documents with non empty `genres`?

2023-01-19 19:58 UTC, letsintegreat commented on lib/data/entry.dart
> +  final List<String> genres;
@stnguyen90 Yes and Yes...

![image](https://user-images.githubusercontent.com/37345795/213546878-ba450062-e014-49c7-ae97-4444c8c97ce3.png)

![image](https://user-images.githubusercontent.com/37345795/213546948-281ce93f-4c5a-4da1-ad33-21eebfdc4c2c.png)

2023-01-20 21:48 UTC, stnguyen90 commented on lib/data/entry.dart
> +  final List<String> genres;
@letsintegreat, what version of Flutter do you have? I have:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6.2 21G320 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

`data` is this for me:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1477010/213810046-494aefc1-c5f5-455a-b502-60dae78017ec.png">

I think this type of error is pretty common. See this sample in [Zapp](https://zapp.run/edit/dart-z11y062t11z0?lazy=false&split=50&entry=lib/main.dart&file=lib/main.dart).

```dart
import 'dart:convert';

void main() {
  String body = '{"genres": ["Action", "Adventure", "Fantasy"]}';
  final data = jsonDecode(body);
  
  print(data);
  print(data['genres']);
  print(data['genres'].runtimeType);
  
  List<String> genres = data['genres'];
}
```

2023-01-22 10:47 UTC, letsintegreat commented on lib/data/entry.dart
> +  final List<String> genres;
@stnguyen90 Ah, I am sorry I was testing the app on a different branch. Yes, you are right, this was indeed a problem. I have fixed this and a few other bugs, and have tested the app thoroughly this time *in the correct branch*. Sorry for the inconvenience!

2023-02-09 22:52 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2023-02-14 17:40 UTC, christyjacob4 approved these changes

2023-02-14 17:41 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

2023-02-14 17:41 UTC, merged